name: build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/{{ .AppOwner }}/{{ .AppName }}
  GITHUB_TOKEN: ${{`{{ secrets.GITHUB_TOKEN }}`}}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # pin@v2.4.1

      - name: Build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v4.0.0
        with:
          load: true
          build-args: |
            APP_TARGET=full
          context: .
          cache-from: |
            type=gha
            type=registry,ref=${{`{{ env.IMAGE_NAME }}`}}:latest
            type=registry,ref=${{`{{ env.IMAGE_NAME }}`}}:buildcache
          cache-to: |
            type=gha
          tags: ${{`{{ env.IMAGE_NAME }}`}}:latest
          target: full

      # cspell: words ghaction
      - name: Import SOPS GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # pin@v5.2.0
        with:
          gpg_private_key: ${{`{{ secrets.SOPS_GPG_PRIVATE_KEY }}`}}

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Create Release
        # Change to support different release channels
        # Versions from a non-main branch will look like: `v.0.0.0-branch-name`.
        if: contains(fromJSON('["main", "beta"]'), github.ref_name)
        run: make release
        env:
          # Using a PAT so we trigger the release workflow
          # (the default token does not trigger events).
          GITHUB_TOKEN: ${{`{{ secrets.GH_PAT }}`}}
